services:
  app:
    image: fuxiaochen:latest
    container_name: fuxiaochen
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_DBNAME=fuxiaochen
      - DATABASE_NAME=fuxiaochen
      - DATABASE_URL=postgresql://postgres:123456@postgresql:5432/fuxiaochen
    networks:
      - fuxiaochen-network
    depends_on:
      - postgresql

  postgresql:
    image: postgres:17
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fuxiaochen
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c timezone=Asia/Shanghai
    networks:
      - fuxiaochen-network

networks:
  fuxiaochen-network:
    driver: bridge

volumes:
  postgres_data:
