export const ERROR_CODES = {
  COMMON_INVALID_REQUEST: "COMMON_INVALID_REQUEST",
  COMMON_VALIDATION_ERROR: "COMMON_VALIDATION_ERROR",
  COMMON_INTERNAL_ERROR: "COMMON_INTERNAL_ERROR",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_SLUG_CONFLICT: "CATEGORY_SLUG_CONFLICT",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",
  TAG_SLUG_CONFLICT: "TAG_SLUG_CONFLICT",
  BLOG_NOT_FOUND: "BLOG_NOT_FOUND",
  BLOG_SLUG_CONFLICT: "BLOG_SLUG_CONFLICT",
  BLOG_CATEGORY_NOT_FOUND: "BLOG_CATEGORY_NOT_FOUND",
  BLOG_TAGS_NOT_FOUND: "BLOG_TAGS_NOT_FOUND",
  CHANGELOG_NOT_FOUND: "CHANGELOG_NOT_FOUND",
  CHANGELOG_VERSION_CONFLICT: "CHANGELOG_VERSION_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
