// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from "@prisma/orm-sqlite/adapter/codec-types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-sqlite/contract/types";
import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-sqlite/family-contract/types";

export type StorageHash =
  StorageHashBase<"10f95d353ed756c27bb78d81421a5d34bfe83fa1476e59965d7da22a2bb25e69">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<"260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53">;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/real@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "sqlite/bigintnumber@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "sqlite/bigintnumber@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "sqlite/bigint@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "sqlite/bigint@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/blob@1": { readonly output: "sqlite/blob@1"; readonly nullable: true };
      readonly "sqlite/datetime@1": {
        readonly output: "sqlite/datetime@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/integer@1"; readonly nullable: true };
      readonly "sqlite/json@1": { readonly output: "sqlite/json@1"; readonly nullable: true };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/text@1": { readonly output: "sqlite/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/blob@1": { readonly output: "sqlite/blob@1"; readonly nullable: true };
      readonly "sqlite/datetime@1": {
        readonly output: "sqlite/datetime@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/integer@1"; readonly nullable: true };
      readonly "sqlite/json@1": { readonly output: "sqlite/json@1"; readonly nullable: true };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/text@1": { readonly output: "sqlite/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sqlite/bigintnumber@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "sql/int@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigint@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly username: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly Category: {
      readonly color: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly Comment: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"] | null;
      readonly author: CodecTypes["sqlite/text@1"]["output"];
      readonly content: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly email: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly parentId: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly postId: CodecTypes["sqlite/text@1"]["output"];
      readonly status: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly version: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly LoginRateLimit: {
      readonly count: CodecTypes["sqlite/integer@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly window: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly Media: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly bytes: CodecTypes["sqlite/integer@1"]["output"] | null;
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly deletedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly expectedBytes: CodecTypes["sqlite/integer@1"]["output"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly height: CodecTypes["sqlite/integer@1"]["output"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly kind: CodecTypes["sqlite/text@1"]["output"];
      readonly leaseToken: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly leaseUntil: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly mime: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly objectKey: CodecTypes["sqlite/text@1"]["output"];
      readonly sha256: CodecTypes["sqlite/text@1"]["output"];
      readonly stagingCleanedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly stagingKey: CodecTypes["sqlite/text@1"]["output"];
      readonly status: CodecTypes["sqlite/text@1"]["output"];
      readonly uploadedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly width: CodecTypes["sqlite/integer@1"]["output"] | null;
    };
    readonly MediaUploadLimit: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly count: CodecTypes["sqlite/integer@1"]["output"];
      readonly window: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly Post: {
      readonly categoryId: CodecTypes["sqlite/text@1"]["output"];
      readonly content: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly publishedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly scheduledFor: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly status: CodecTypes["sqlite/text@1"]["output"];
      readonly title: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly version: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly PostTag: {
      readonly postId: CodecTypes["sqlite/text@1"]["output"];
      readonly tagId: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly Session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly Tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly username: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly Category: {
      readonly color: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly Comment: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"] | null;
      readonly author: CodecTypes["sqlite/text@1"]["input"];
      readonly content: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly email: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly parentId: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly postId: CodecTypes["sqlite/text@1"]["input"];
      readonly status: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly version: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly LoginRateLimit: {
      readonly count: CodecTypes["sqlite/integer@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly window: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly Media: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly bytes: CodecTypes["sqlite/integer@1"]["input"] | null;
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly deletedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly expectedBytes: CodecTypes["sqlite/integer@1"]["input"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly height: CodecTypes["sqlite/integer@1"]["input"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly kind: CodecTypes["sqlite/text@1"]["input"];
      readonly leaseToken: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly leaseUntil: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly mime: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly objectKey: CodecTypes["sqlite/text@1"]["input"];
      readonly sha256: CodecTypes["sqlite/text@1"]["input"];
      readonly stagingCleanedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly stagingKey: CodecTypes["sqlite/text@1"]["input"];
      readonly status: CodecTypes["sqlite/text@1"]["input"];
      readonly uploadedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly width: CodecTypes["sqlite/integer@1"]["input"] | null;
    };
    readonly MediaUploadLimit: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly count: CodecTypes["sqlite/integer@1"]["input"];
      readonly window: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly Post: {
      readonly categoryId: CodecTypes["sqlite/text@1"]["input"];
      readonly content: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly publishedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly scheduledFor: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly status: CodecTypes["sqlite/text@1"]["input"];
      readonly title: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly version: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly PostTag: {
      readonly postId: CodecTypes["sqlite/text@1"]["input"];
      readonly tagId: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly Session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly Tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly username: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly category: {
      readonly color: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly comment: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"] | null;
      readonly author: CodecTypes["sqlite/text@1"]["output"];
      readonly content: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly email: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly parentId: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly postId: CodecTypes["sqlite/text@1"]["output"];
      readonly status: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly version: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly login_rate_limit: {
      readonly count: CodecTypes["sqlite/integer@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly window: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly media: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly bytes: CodecTypes["sqlite/integer@1"]["output"] | null;
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly deletedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly expectedBytes: CodecTypes["sqlite/integer@1"]["output"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly height: CodecTypes["sqlite/integer@1"]["output"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly kind: CodecTypes["sqlite/text@1"]["output"];
      readonly leaseToken: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly leaseUntil: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly mime: CodecTypes["sqlite/text@1"]["output"] | null;
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly objectKey: CodecTypes["sqlite/text@1"]["output"];
      readonly sha256: CodecTypes["sqlite/text@1"]["output"];
      readonly stagingCleanedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly stagingKey: CodecTypes["sqlite/text@1"]["output"];
      readonly status: CodecTypes["sqlite/text@1"]["output"];
      readonly uploadedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly width: CodecTypes["sqlite/integer@1"]["output"] | null;
    };
    readonly media_upload_limit: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly count: CodecTypes["sqlite/integer@1"]["output"];
      readonly window: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly post: {
      readonly categoryId: CodecTypes["sqlite/text@1"]["output"];
      readonly content: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly publishedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly scheduledFor: CodecTypes["sqlite/datetime@1"]["output"] | null;
      readonly status: CodecTypes["sqlite/text@1"]["output"];
      readonly title: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly version: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly post_tag: {
      readonly postId: CodecTypes["sqlite/text@1"]["output"];
      readonly tagId: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly username: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly category: {
      readonly color: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly comment: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"] | null;
      readonly author: CodecTypes["sqlite/text@1"]["input"];
      readonly content: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly email: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly parentId: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly postId: CodecTypes["sqlite/text@1"]["input"];
      readonly status: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly version: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly login_rate_limit: {
      readonly count: CodecTypes["sqlite/integer@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly window: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly media: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly bytes: CodecTypes["sqlite/integer@1"]["input"] | null;
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly deletedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly expectedBytes: CodecTypes["sqlite/integer@1"]["input"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly height: CodecTypes["sqlite/integer@1"]["input"] | null;
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly kind: CodecTypes["sqlite/text@1"]["input"];
      readonly leaseToken: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly leaseUntil: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly mime: CodecTypes["sqlite/text@1"]["input"] | null;
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly objectKey: CodecTypes["sqlite/text@1"]["input"];
      readonly sha256: CodecTypes["sqlite/text@1"]["input"];
      readonly stagingCleanedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly stagingKey: CodecTypes["sqlite/text@1"]["input"];
      readonly status: CodecTypes["sqlite/text@1"]["input"];
      readonly uploadedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly width: CodecTypes["sqlite/integer@1"]["input"] | null;
    };
    readonly media_upload_limit: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly count: CodecTypes["sqlite/integer@1"]["input"];
      readonly window: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly post: {
      readonly categoryId: CodecTypes["sqlite/text@1"]["input"];
      readonly content: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly publishedAt: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly scheduledFor: CodecTypes["sqlite/datetime@1"]["input"] | null;
      readonly status: CodecTypes["sqlite/text@1"]["input"];
      readonly title: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly version: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly post_tag: {
      readonly postId: CodecTypes["sqlite/text@1"]["input"];
      readonly tagId: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
  };
};

export namespace Models {
  export type Admin = {
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/integer@1"]["output"];
    passwordHash: CodecTypes["sqlite/text@1"]["output"];
    updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
    username: CodecTypes["sqlite/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type Category = {
    color: CodecTypes["sqlite/text@1"]["output"];
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    name: CodecTypes["sqlite/text@1"]["output"];
    nameKey: CodecTypes["sqlite/text@1"]["output"];
    posts: Post[];
    readonly [RelationKeys]?: "posts";
  };
  export type Comment = {
    adminId: CodecTypes["sqlite/integer@1"]["output"] | null;
    author: CodecTypes["sqlite/text@1"]["output"];
    content: CodecTypes["sqlite/text@1"]["output"];
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    email: CodecTypes["sqlite/text@1"]["output"] | null;
    id: CodecTypes["sqlite/text@1"]["output"];
    parentId: CodecTypes["sqlite/text@1"]["output"] | null;
    postId: CodecTypes["sqlite/text@1"]["output"];
    status: CodecTypes["sqlite/text@1"]["output"];
    updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
    version: CodecTypes["sqlite/integer@1"]["output"];
    admin: Admin | null;
    parent: Comment | null;
    post: Post;
    replies: Comment[];
    readonly [RelationKeys]?: "admin" | "parent" | "post" | "replies";
  };
  export type LoginRateLimit = {
    count: CodecTypes["sqlite/integer@1"]["output"];
    id: CodecTypes["sqlite/integer@1"]["output"];
    window: CodecTypes["sqlite/integer@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type Media = {
    adminId: CodecTypes["sqlite/integer@1"]["output"];
    bytes: CodecTypes["sqlite/integer@1"]["output"] | null;
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    deletedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
    expectedBytes: CodecTypes["sqlite/integer@1"]["output"];
    expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
    height: CodecTypes["sqlite/integer@1"]["output"] | null;
    id: CodecTypes["sqlite/text@1"]["output"];
    kind: CodecTypes["sqlite/text@1"]["output"];
    leaseToken: CodecTypes["sqlite/text@1"]["output"] | null;
    leaseUntil: CodecTypes["sqlite/datetime@1"]["output"] | null;
    mime: CodecTypes["sqlite/text@1"]["output"] | null;
    name: CodecTypes["sqlite/text@1"]["output"];
    objectKey: CodecTypes["sqlite/text@1"]["output"];
    sha256: CodecTypes["sqlite/text@1"]["output"];
    stagingCleanedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
    stagingKey: CodecTypes["sqlite/text@1"]["output"];
    status: CodecTypes["sqlite/text@1"]["output"];
    uploadedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
    width: CodecTypes["sqlite/integer@1"]["output"] | null;
    readonly [RelationKeys]?: never;
  };
  export type MediaUploadLimit = {
    adminId: CodecTypes["sqlite/integer@1"]["output"];
    count: CodecTypes["sqlite/integer@1"]["output"];
    window: CodecTypes["sqlite/integer@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type Post = {
    categoryId: CodecTypes["sqlite/text@1"]["output"];
    content: CodecTypes["sqlite/text@1"]["output"];
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    publishedAt: CodecTypes["sqlite/datetime@1"]["output"] | null;
    scheduledFor: CodecTypes["sqlite/datetime@1"]["output"] | null;
    status: CodecTypes["sqlite/text@1"]["output"];
    title: CodecTypes["sqlite/text@1"]["output"];
    updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
    version: CodecTypes["sqlite/integer@1"]["output"];
    category: Category;
    comments: Comment[];
    tagLinks: PostTag[];
    readonly [RelationKeys]?: "category" | "comments" | "tagLinks";
  };
  export type PostTag = {
    postId: CodecTypes["sqlite/text@1"]["output"];
    tagId: CodecTypes["sqlite/text@1"]["output"];
    post: Post;
    tag: Tag;
    readonly [RelationKeys]?: "post" | "tag";
  };
  export type Session = {
    adminId: CodecTypes["sqlite/integer@1"]["output"];
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    admin: Admin;
    readonly [RelationKeys]?: "admin";
  };
  export type Tag = {
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    name: CodecTypes["sqlite/text@1"]["output"];
    nameKey: CodecTypes["sqlite/text@1"]["output"];
    postLinks: PostTag[];
    readonly [RelationKeys]?: "postLinks";
  };
}

export declare const models: {
  Admin: Models.Admin;
  Category: Models.Category;
  Comment: Models.Comment;
  LoginRateLimit: Models.LoginRateLimit;
  Media: Models.Media;
  MediaUploadLimit: Models.MediaUploadLimit;
  Post: Models.Post;
  PostTag: Models.PostTag;
  Session: Models.Session;
  Tag: Models.Tag;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: "__unbound__";
        readonly kind: "sqlite-namespace";
        readonly entries: {
          readonly table: {
            readonly admin: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["username"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly category: {
              columns: {
                readonly color: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly nameKey: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["nameKey"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly comment: {
              columns: {
                readonly adminId: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: true;
                };
                readonly author: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly parentId: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: true;
                };
                readonly postId: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["id", "postId"] }];
              indexes: readonly [
                {
                  readonly name: "comment_adminId_idx_530179db";
                  readonly prefix: "comment_adminId_idx";
                  readonly columns: readonly ["adminId"];
                  readonly unique: false;
                },
                {
                  readonly name: "comment_createdAt_id_idx_3855cff1";
                  readonly prefix: "comment_createdAt_id_idx";
                  readonly columns: readonly ["createdAt", "id"];
                  readonly unique: false;
                },
                {
                  readonly name: "comment_parentId_idx_6a68f597";
                  readonly prefix: "comment_parentId_idx";
                  readonly columns: readonly ["parentId"];
                  readonly unique: false;
                },
                {
                  readonly name: "comment_parentId_postId_idx_1317b68e";
                  readonly prefix: "comment_parentId_postId_idx";
                  readonly columns: readonly ["parentId", "postId"];
                  readonly unique: false;
                },
                {
                  readonly name: "comment_postId_idx_a7a72715";
                  readonly prefix: "comment_postId_idx";
                  readonly columns: readonly ["postId"];
                  readonly unique: false;
                },
                {
                  readonly name: "comment_status_createdAt_id_idx_ffb42ad8";
                  readonly prefix: "comment_status_createdAt_id_idx";
                  readonly columns: readonly ["status", "createdAt", "id"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "comment";
                    readonly columns: readonly ["postId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "post";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "comment";
                    readonly columns: readonly ["parentId", "postId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "comment";
                    readonly columns: readonly ["id", "postId"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "comment";
                    readonly columns: readonly ["adminId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "admin";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly login_rate_limit: {
              columns: {
                readonly count: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly window: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly media: {
              columns: {
                readonly adminId: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly bytes: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly deletedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: true;
                };
                readonly expectedBytes: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly height: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly kind: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly leaseToken: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: true;
                };
                readonly leaseUntil: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: true;
                };
                readonly mime: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly objectKey: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly sha256: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly stagingCleanedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: true;
                };
                readonly stagingKey: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly uploadedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: true;
                };
                readonly width: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [
                { readonly columns: readonly ["stagingKey"] },
                { readonly columns: readonly ["objectKey"] },
              ];
              indexes: readonly [
                {
                  readonly name: "media_adminId_idx_530179db";
                  readonly prefix: "media_adminId_idx";
                  readonly columns: readonly ["adminId"];
                  readonly unique: false;
                },
                {
                  readonly name: "media_createdAt_id_idx_3855cff1";
                  readonly prefix: "media_createdAt_id_idx";
                  readonly columns: readonly ["createdAt", "id"];
                  readonly unique: false;
                },
                {
                  readonly name: "media_status_expiresAt_idx_c206f415";
                  readonly prefix: "media_status_expiresAt_idx";
                  readonly columns: readonly ["status", "expiresAt"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "media";
                    readonly columns: readonly ["adminId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "admin";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly media_upload_limit: {
              columns: {
                readonly adminId: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly count: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly window: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["adminId"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "media_upload_limit";
                    readonly columns: readonly ["adminId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "admin";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly post: {
              columns: {
                readonly categoryId: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly publishedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: true;
                };
                readonly scheduledFor: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly version: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "post_categoryId_idx_15c304f2";
                  readonly prefix: "post_categoryId_idx";
                  readonly columns: readonly ["categoryId"];
                  readonly unique: false;
                },
                {
                  readonly name: "post_createdAt_id_idx_3855cff1";
                  readonly prefix: "post_createdAt_id_idx";
                  readonly columns: readonly ["createdAt", "id"];
                  readonly unique: false;
                },
                {
                  readonly name: "post_status_scheduledFor_idx_e20b7d95";
                  readonly prefix: "post_status_scheduledFor_idx";
                  readonly columns: readonly ["status", "scheduledFor"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "post";
                    readonly columns: readonly ["categoryId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "category";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly post_tag: {
              columns: {
                readonly postId: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly tagId: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["postId", "tagId"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "post_tag_postId_idx_a7a72715";
                  readonly prefix: "post_tag_postId_idx";
                  readonly columns: readonly ["postId"];
                  readonly unique: false;
                },
                {
                  readonly name: "post_tag_tagId_idx_86854244";
                  readonly prefix: "post_tag_tagId_idx";
                  readonly columns: readonly ["tagId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "post_tag";
                    readonly columns: readonly ["postId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "post";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "post_tag";
                    readonly columns: readonly ["tagId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "tag";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly session: {
              columns: {
                readonly adminId: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "session_adminId_idx_530179db";
                  readonly prefix: "session_adminId_idx";
                  readonly columns: readonly ["adminId"];
                  readonly unique: false;
                },
                {
                  readonly name: "session_expiresAt_idx_6b6b8c10";
                  readonly prefix: "session_expiresAt_idx";
                  readonly columns: readonly ["expiresAt"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "session";
                    readonly columns: readonly ["adminId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "admin";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly tag: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly nameKey: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["nameKey"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "sqlite";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly admin: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Admin" };
    readonly category: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "Category";
    };
    readonly comment: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "Comment";
    };
    readonly login_rate_limit: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "LoginRateLimit";
    };
    readonly media: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Media" };
    readonly media_upload_limit: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "MediaUploadLimit";
    };
    readonly post: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Post" };
    readonly post_tag: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "PostTag";
    };
    readonly session: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "Session";
    };
    readonly tag: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Tag" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Admin: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "admin";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly passwordHash: { readonly column: "passwordHash" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly username: { readonly column: "username" };
              };
            };
          };
          readonly Category: {
            readonly fields: {
              readonly color: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly nameKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: {
              readonly posts: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Post";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["categoryId"];
                };
              };
            };
            readonly storage: {
              readonly table: "category";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly color: { readonly column: "color" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly nameKey: { readonly column: "nameKey" };
              };
            };
          };
          readonly Comment: {
            readonly fields: {
              readonly adminId: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly author: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly parentId: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly postId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
            };
            readonly relations: {
              readonly admin: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Admin";
                };
                readonly cardinality: "N:1";
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ["adminId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly parent: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Comment";
                };
                readonly cardinality: "N:1";
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ["parentId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly post: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Post";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["postId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly replies: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Comment";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["parentId"];
                };
              };
            };
            readonly storage: {
              readonly table: "comment";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly adminId: { readonly column: "adminId" };
                readonly author: { readonly column: "author" };
                readonly content: { readonly column: "content" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly email: { readonly column: "email" };
                readonly id: { readonly column: "id" };
                readonly parentId: { readonly column: "parentId" };
                readonly postId: { readonly column: "postId" };
                readonly status: { readonly column: "status" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly version: { readonly column: "version" };
              };
            };
          };
          readonly LoginRateLimit: {
            readonly fields: {
              readonly count: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly window: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "login_rate_limit";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly count: { readonly column: "count" };
                readonly id: { readonly column: "id" };
                readonly window: { readonly column: "window" };
              };
            };
          };
          readonly Media: {
            readonly fields: {
              readonly adminId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly bytes: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly deletedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly expectedBytes: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly height: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly leaseToken: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly leaseUntil: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly mime: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly objectKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly sha256: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly stagingCleanedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly stagingKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly uploadedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly width: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "media";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly adminId: { readonly column: "adminId" };
                readonly bytes: { readonly column: "bytes" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly deletedAt: { readonly column: "deletedAt" };
                readonly expectedBytes: { readonly column: "expectedBytes" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly height: { readonly column: "height" };
                readonly id: { readonly column: "id" };
                readonly kind: { readonly column: "kind" };
                readonly leaseToken: { readonly column: "leaseToken" };
                readonly leaseUntil: { readonly column: "leaseUntil" };
                readonly mime: { readonly column: "mime" };
                readonly name: { readonly column: "name" };
                readonly objectKey: { readonly column: "objectKey" };
                readonly sha256: { readonly column: "sha256" };
                readonly stagingCleanedAt: { readonly column: "stagingCleanedAt" };
                readonly stagingKey: { readonly column: "stagingKey" };
                readonly status: { readonly column: "status" };
                readonly uploadedAt: { readonly column: "uploadedAt" };
                readonly width: { readonly column: "width" };
              };
            };
          };
          readonly MediaUploadLimit: {
            readonly fields: {
              readonly adminId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly count: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly window: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "media_upload_limit";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly adminId: { readonly column: "adminId" };
                readonly count: { readonly column: "count" };
                readonly window: { readonly column: "window" };
              };
            };
          };
          readonly Post: {
            readonly fields: {
              readonly categoryId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly scheduledFor: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly version: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Category";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["categoryId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly comments: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Comment";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["postId"];
                };
              };
              readonly tagLinks: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "PostTag";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["postId"];
                };
              };
            };
            readonly storage: {
              readonly table: "post";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly categoryId: { readonly column: "categoryId" };
                readonly content: { readonly column: "content" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly publishedAt: { readonly column: "publishedAt" };
                readonly scheduledFor: { readonly column: "scheduledFor" };
                readonly status: { readonly column: "status" };
                readonly title: { readonly column: "title" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly version: { readonly column: "version" };
              };
            };
          };
          readonly PostTag: {
            readonly fields: {
              readonly postId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly tagId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: {
              readonly post: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Post";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["postId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly tag: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Tag";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["tagId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "post_tag";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly postId: { readonly column: "postId" };
                readonly tagId: { readonly column: "tagId" };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly adminId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: {
              readonly admin: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Admin";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["adminId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "session";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly adminId: { readonly column: "adminId" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly id: { readonly column: "id" };
              };
            };
          };
          readonly Tag: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly nameKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: {
              readonly postLinks: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "PostTag";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["tagId"];
                };
              };
            };
            readonly storage: {
              readonly table: "tag";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly nameKey: { readonly column: "nameKey" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly foreignKeys: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly jsonAgg: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
