#!/usr/bin/env -S node
import { Migration, MigrationCLI, col, lit, primaryKey } from "@prisma/orm-postgres/migration";

import type { Contract as End } from "../../snapshots/4034c730654ca13b0fa6eb03cc03aed204c6d65226eccc6a605b2add5bb65d44/contract";

import endContract from "../../snapshots/4034c730654ca13b0fa6eb03cc03aed204c6d65226eccc6a605b2add5bb65d44/contract.json" with { type: "json" };

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: "public" }),
      this.createTable({
        schema: "public",
        table: "admin",
        columns: [
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("passwordHash", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("updatedAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("username", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "analytics_rate_limit",
        columns: [
          col("count", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("expiresAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("window", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "backup_run",
        columns: [
          col("bytes", "int8", { codecRef: { codecId: "pg/int8number@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("dailyKey", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("finishedAt", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("sha256", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("status", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "category",
        columns: [
          col("color", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("name", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("nameKey", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "comment",
        columns: [
          col("adminId", "int8", { codecRef: { codecId: "pg/int8number@1" } }),
          col("author", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("authorKind", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("content", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("email", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("parentId", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("postId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("status", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("submissionHash", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("submissionId", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("updatedAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("version", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "comment_rate_limit",
        columns: [
          col("count", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("expiresAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("window", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "friend_link",
        columns: [
          col("avatar", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("category", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("description", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("enabled", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("name", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("status", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("updatedAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("url", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("version", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "login_rate_limit",
        columns: [
          col("count", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("id", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("window", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "media",
        columns: [
          col("adminId", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("bytes", "int8", { codecRef: { codecId: "pg/int8number@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("deletedAt", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("expectedBytes", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("expiresAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("height", "int8", { codecRef: { codecId: "pg/int8number@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("kind", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("leaseToken", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("leaseUntil", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("mime", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("name", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("objectKey", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("sha256", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("stagingCleanedAt", "timestamptz", {
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("stagingKey", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("status", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("uploadedAt", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("width", "int8", { codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "media_upload_limit",
        columns: [
          col("adminId", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("count", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("window", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["adminId"])],
      }),
      this.createTable({
        schema: "public",
        table: "notification",
        columns: [
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("href", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("kind", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("resolvedAt", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("sourceId", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("title", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "notification_read",
        columns: [
          col("adminId", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("notificationId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("readAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
        ],
        constraints: [primaryKey(["notificationId", "adminId"])],
      }),
      this.createTable({
        schema: "public",
        table: "operation_setting",
        columns: [
          col("autoBackup", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("id", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("schedulerLastRunAt", "timestamptz", {
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("updatedAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("version", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "page_visit",
        columns: [
          col("article", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("browser", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("device", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("durationMs", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("ip", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("lastSeenAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("location", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("os", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("path", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("postId", "text", { codecRef: { codecId: "pg/text@1" } }),
          col("progress", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("referrerHost", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("sessionId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("source", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("visitorHash", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "post",
        columns: [
          col("categoryId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("content", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("featuredOrder", "int8", {
            notNull: true,
            default: lit("0"),
            codecRef: { codecId: "pg/int8number@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("isFeatured", "int8", {
            notNull: true,
            default: lit("0"),
            codecRef: { codecId: "pg/int8number@1" },
          }),
          col("publishedAt", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("scheduledFor", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("slug", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("slugLockedAt", "timestamptz", { codecRef: { codecId: "pg/timestamptz-date@1" } }),
          col("status", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("summary", "text", {
            notNull: true,
            default: lit(""),
            codecRef: { codecId: "pg/text@1" },
          }),
          col("title", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("updatedAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("version", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "post_tag",
        columns: [
          col("postId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("tagId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["postId", "tagId"])],
      }),
      this.createTable({
        schema: "public",
        table: "release_log",
        columns: [
          col("changes", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("title", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("type", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("version", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "session",
        columns: [
          col("adminId", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("expiresAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "site_setting",
        columns: [
          col("aboutMe", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("authorName", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("authorRole", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("avatarUrl", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("baiduEnabled", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("baiduId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("enableComments", "int8", {
            notNull: true,
            codecRef: { codecId: "pg/int8number@1" },
          }),
          col("googleEnabled", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("googleId", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("icpText", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("icpUrl", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("id", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("localAnalyticsEnabled", "int8", { codecRef: { codecId: "pg/int8number@1" } }),
          col("localAnalyticsStartedAt", "timestamptz", {
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("policeText", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("policeUrl", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("postsPerPage", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("subtitle", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("title", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("updatedAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("version", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "social_account",
        columns: [
          col("enabled", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("icon", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("imageUrl", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("label", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("position", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("settingId", "int8", { notNull: true, codecRef: { codecId: "pg/int8number@1" } }),
          col("url", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "tag",
        columns: [
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("name", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("nameKey", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.createTable({
        schema: "public",
        table: "visit_session",
        columns: [
          col("createdAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("id", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
          col("lastSeenAt", "timestamptz", {
            notNull: true,
            codecRef: { codecId: "pg/timestamptz-date@1" },
          }),
          col("visitorHash", "text", { notNull: true, codecRef: { codecId: "pg/text@1" } }),
        ],
        constraints: [primaryKey(["id"])],
      }),
      this.addUnique({
        schema: "public",
        table: "admin",
        constraint: "admin_username_key",
        columns: ["username"],
      }),
      this.addUnique({
        schema: "public",
        table: "backup_run",
        constraint: "backup_run_dailyKey_key",
        columns: ["dailyKey"],
      }),
      this.addUnique({
        schema: "public",
        table: "category",
        constraint: "category_nameKey_key",
        columns: ["nameKey"],
      }),
      this.addUnique({
        schema: "public",
        table: "comment",
        constraint: "comment_submissionId_key",
        columns: ["submissionId"],
      }),
      this.addUnique({
        schema: "public",
        table: "comment",
        constraint: "comment_id_postId_key",
        columns: ["id", "postId"],
      }),
      this.addUnique({
        schema: "public",
        table: "media",
        constraint: "media_stagingKey_key",
        columns: ["stagingKey"],
      }),
      this.addUnique({
        schema: "public",
        table: "media",
        constraint: "media_objectKey_key",
        columns: ["objectKey"],
      }),
      this.addUnique({
        schema: "public",
        table: "post",
        constraint: "post_slug_key",
        columns: ["slug"],
      }),
      this.addUnique({
        schema: "public",
        table: "tag",
        constraint: "tag_nameKey_key",
        columns: ["nameKey"],
      }),
      this.createIndex({
        schema: "public",
        table: "analytics_rate_limit",
        index: "analytics_rate_limit_expiresAt_idx_6b6b8c10",
        columns: ["expiresAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "backup_run",
        index: "backup_run_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment",
        index: "comment_adminId_idx_530179db",
        columns: ["adminId"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment",
        index: "comment_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment",
        index: "comment_parentId_idx_6a68f597",
        columns: ["parentId"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment",
        index: "comment_parentId_postId_idx_1317b68e",
        columns: ["parentId", "postId"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment",
        index: "comment_postId_idx_a7a72715",
        columns: ["postId"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment",
        index: "comment_status_createdAt_id_idx_ffb42ad8",
        columns: ["status", "createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "comment_rate_limit",
        index: "comment_rate_limit_expiresAt_idx_6b6b8c10",
        columns: ["expiresAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "friend_link",
        index: "friend_link_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "friend_link",
        index: "friend_link_status_enabled_idx_d0122654",
        columns: ["status", "enabled"],
      }),
      this.createIndex({
        schema: "public",
        table: "media",
        index: "media_adminId_idx_530179db",
        columns: ["adminId"],
      }),
      this.createIndex({
        schema: "public",
        table: "media",
        index: "media_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "media",
        index: "media_status_expiresAt_idx_c206f415",
        columns: ["status", "expiresAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "notification",
        index: "notification_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "notification_read",
        index: "notification_read_adminId_idx_530179db",
        columns: ["adminId"],
      }),
      this.createIndex({
        schema: "public",
        table: "notification_read",
        index: "notification_read_notificationId_idx_adfe2654",
        columns: ["notificationId"],
      }),
      this.createIndex({
        schema: "public",
        table: "page_visit",
        index: "page_visit_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "page_visit",
        index: "page_visit_lastSeenAt_idx_b69845da",
        columns: ["lastSeenAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "page_visit",
        index: "page_visit_postId_createdAt_idx_b244c517",
        columns: ["postId", "createdAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "page_visit",
        index: "page_visit_postId_idx_a7a72715",
        columns: ["postId"],
      }),
      this.createIndex({
        schema: "public",
        table: "page_visit",
        index: "page_visit_sessionId_idx_29f415d4",
        columns: ["sessionId"],
      }),
      this.createIndex({
        schema: "public",
        table: "page_visit",
        index: "page_visit_visitorHash_lastSeenAt_idx_484f4b5e",
        columns: ["visitorHash", "lastSeenAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "post",
        index: "post_categoryId_idx_15c304f2",
        columns: ["categoryId"],
      }),
      this.createIndex({
        schema: "public",
        table: "post",
        index: "post_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "post",
        index: "post_status_publishedAt_id_idx_a01ed76d",
        columns: ["status", "publishedAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "post",
        index: "post_status_scheduledFor_idx_e20b7d95",
        columns: ["status", "scheduledFor"],
      }),
      this.createIndex({
        schema: "public",
        table: "post_tag",
        index: "post_tag_postId_idx_a7a72715",
        columns: ["postId"],
      }),
      this.createIndex({
        schema: "public",
        table: "post_tag",
        index: "post_tag_tagId_idx_86854244",
        columns: ["tagId"],
      }),
      this.createIndex({
        schema: "public",
        table: "release_log",
        index: "release_log_createdAt_id_idx_3855cff1",
        columns: ["createdAt", "id"],
      }),
      this.createIndex({
        schema: "public",
        table: "session",
        index: "session_adminId_idx_530179db",
        columns: ["adminId"],
      }),
      this.createIndex({
        schema: "public",
        table: "session",
        index: "session_expiresAt_idx_6b6b8c10",
        columns: ["expiresAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "social_account",
        index: "social_account_settingId_idx_c16f9ff8",
        columns: ["settingId"],
      }),
      this.createIndex({
        schema: "public",
        table: "social_account",
        index: "social_account_settingId_position_idx_e0140a9b",
        columns: ["settingId", "position"],
      }),
      this.createIndex({
        schema: "public",
        table: "visit_session",
        index: "visit_session_createdAt_idx_9575dbd7",
        columns: ["createdAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "visit_session",
        index: "visit_session_lastSeenAt_idx_b69845da",
        columns: ["lastSeenAt"],
      }),
      this.createIndex({
        schema: "public",
        table: "visit_session",
        index: "visit_session_visitorHash_lastSeenAt_idx_484f4b5e",
        columns: ["visitorHash", "lastSeenAt"],
      }),
      this.addForeignKey({
        schema: "public",
        table: "comment",
        foreignKey: {
          name: "comment_postId_fkey",
          columns: ["postId"],
          references: { schema: "public", table: "post", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "comment",
        foreignKey: {
          name: "comment_parentId_postId_fkey",
          columns: ["parentId", "postId"],
          references: { schema: "public", table: "comment", columns: ["id", "postId"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "comment",
        foreignKey: {
          name: "comment_adminId_fkey",
          columns: ["adminId"],
          references: { schema: "public", table: "admin", columns: ["id"] },
          onDelete: "setNull",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "media",
        foreignKey: {
          name: "media_adminId_fkey",
          columns: ["adminId"],
          references: { schema: "public", table: "admin", columns: ["id"] },
          onDelete: "restrict",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "media_upload_limit",
        foreignKey: {
          name: "media_upload_limit_adminId_fkey",
          columns: ["adminId"],
          references: { schema: "public", table: "admin", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "notification_read",
        foreignKey: {
          name: "notification_read_notificationId_fkey",
          columns: ["notificationId"],
          references: { schema: "public", table: "notification", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "notification_read",
        foreignKey: {
          name: "notification_read_adminId_fkey",
          columns: ["adminId"],
          references: { schema: "public", table: "admin", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "page_visit",
        foreignKey: {
          name: "page_visit_sessionId_fkey",
          columns: ["sessionId"],
          references: { schema: "public", table: "visit_session", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "page_visit",
        foreignKey: {
          name: "page_visit_postId_fkey",
          columns: ["postId"],
          references: { schema: "public", table: "post", columns: ["id"] },
          onDelete: "setNull",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "post",
        foreignKey: {
          name: "post_categoryId_fkey",
          columns: ["categoryId"],
          references: { schema: "public", table: "category", columns: ["id"] },
          onDelete: "restrict",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "post_tag",
        foreignKey: {
          name: "post_tag_postId_fkey",
          columns: ["postId"],
          references: { schema: "public", table: "post", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "post_tag",
        foreignKey: {
          name: "post_tag_tagId_fkey",
          columns: ["tagId"],
          references: { schema: "public", table: "tag", columns: ["id"] },
          onDelete: "restrict",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "session",
        foreignKey: {
          name: "session_adminId_fkey",
          columns: ["adminId"],
          references: { schema: "public", table: "admin", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
      this.addForeignKey({
        schema: "public",
        table: "social_account",
        foreignKey: {
          name: "social_account_settingId_fkey",
          columns: ["settingId"],
          references: { schema: "public", table: "site_setting", columns: ["id"] },
          onDelete: "cascade",
        },
      }),
    ];
  }
}

await MigrationCLI.run(import.meta.url, M);
