// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from "@prisma/orm-sqlite/adapter/codec-types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-sqlite/contract/types";
import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-sqlite/family-contract/types";

export type StorageHash =
  StorageHashBase<"f0b62a75826f509074906baeedbf788bab4bc2a81d71a0b13b0d5e92dd5c44ca">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<"260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53">;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/real@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "sqlite/bigintnumber@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "sqlite/bigintnumber@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "sqlite/bigint@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "sqlite/bigint@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/blob@1": { readonly output: "sqlite/blob@1"; readonly nullable: true };
      readonly "sqlite/datetime@1": {
        readonly output: "sqlite/datetime@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/integer@1"; readonly nullable: true };
      readonly "sqlite/json@1": { readonly output: "sqlite/json@1"; readonly nullable: true };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/text@1": { readonly output: "sqlite/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/blob@1": { readonly output: "sqlite/blob@1"; readonly nullable: true };
      readonly "sqlite/datetime@1": {
        readonly output: "sqlite/datetime@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/integer@1"; readonly nullable: true };
      readonly "sqlite/json@1": { readonly output: "sqlite/json@1"; readonly nullable: true };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sqlite/text@1": { readonly output: "sqlite/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "sql/float@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sqlite/bigintnumber@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": {
        readonly output: "sqlite/bigintnumber@1";
        readonly nullable: true;
      };
      readonly "sqlite/real@1": { readonly output: "sqlite/real@1"; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "sql/int@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigint@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
      readonly "sqlite/bigintnumber@1": {
        readonly output: "sqlite/bigint@1";
        readonly nullable: true;
      };
      readonly "sqlite/integer@1": { readonly output: "sqlite/bigint@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly username: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly Category: {
      readonly color: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly LoginRateLimit: {
      readonly count: CodecTypes["sqlite/integer@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly window: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly Session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly Tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly username: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly Category: {
      readonly color: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly LoginRateLimit: {
      readonly count: CodecTypes["sqlite/integer@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly window: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly Session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly Tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["output"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly username: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly category: {
      readonly color: CodecTypes["sqlite/text@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly login_rate_limit: {
      readonly count: CodecTypes["sqlite/integer@1"]["output"];
      readonly id: CodecTypes["sqlite/integer@1"]["output"];
      readonly window: CodecTypes["sqlite/integer@1"]["output"];
    };
    readonly session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["output"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
    };
    readonly tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["output"];
      readonly id: CodecTypes["sqlite/text@1"]["output"];
      readonly name: CodecTypes["sqlite/text@1"]["output"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly admin: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly passwordHash: CodecTypes["sqlite/text@1"]["input"];
      readonly updatedAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly username: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly category: {
      readonly color: CodecTypes["sqlite/text@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly login_rate_limit: {
      readonly count: CodecTypes["sqlite/integer@1"]["input"];
      readonly id: CodecTypes["sqlite/integer@1"]["input"];
      readonly window: CodecTypes["sqlite/integer@1"]["input"];
    };
    readonly session: {
      readonly adminId: CodecTypes["sqlite/integer@1"]["input"];
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly expiresAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
    };
    readonly tag: {
      readonly createdAt: CodecTypes["sqlite/datetime@1"]["input"];
      readonly id: CodecTypes["sqlite/text@1"]["input"];
      readonly name: CodecTypes["sqlite/text@1"]["input"];
      readonly nameKey: CodecTypes["sqlite/text@1"]["input"];
    };
  };
};

export namespace Models {
  export type Admin = {
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/integer@1"]["output"];
    passwordHash: CodecTypes["sqlite/text@1"]["output"];
    updatedAt: CodecTypes["sqlite/datetime@1"]["output"];
    username: CodecTypes["sqlite/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type Category = {
    color: CodecTypes["sqlite/text@1"]["output"];
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    name: CodecTypes["sqlite/text@1"]["output"];
    nameKey: CodecTypes["sqlite/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type LoginRateLimit = {
    count: CodecTypes["sqlite/integer@1"]["output"];
    id: CodecTypes["sqlite/integer@1"]["output"];
    window: CodecTypes["sqlite/integer@1"]["output"];
    readonly [RelationKeys]?: never;
  };
  export type Session = {
    adminId: CodecTypes["sqlite/integer@1"]["output"];
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    expiresAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    admin: Admin;
    readonly [RelationKeys]?: "admin";
  };
  export type Tag = {
    createdAt: CodecTypes["sqlite/datetime@1"]["output"];
    id: CodecTypes["sqlite/text@1"]["output"];
    name: CodecTypes["sqlite/text@1"]["output"];
    nameKey: CodecTypes["sqlite/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  Admin: Models.Admin;
  Category: Models.Category;
  LoginRateLimit: Models.LoginRateLimit;
  Session: Models.Session;
  Tag: Models.Tag;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: "__unbound__";
        readonly kind: "sqlite-namespace";
        readonly entries: {
          readonly table: {
            readonly admin: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["username"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly category: {
              columns: {
                readonly color: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly nameKey: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["nameKey"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly login_rate_limit: {
              columns: {
                readonly count: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly window: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly session: {
              columns: {
                readonly adminId: {
                  readonly nativeType: "integer";
                  readonly codecId: "sqlite/integer@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "session_adminId_idx_530179db";
                  readonly prefix: "session_adminId_idx";
                  readonly columns: readonly ["adminId"];
                  readonly unique: false;
                },
                {
                  readonly name: "session_expiresAt_idx_6b6b8c10";
                  readonly prefix: "session_expiresAt_idx";
                  readonly columns: readonly ["expiresAt"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "session";
                    readonly columns: readonly ["adminId"];
                  };
                  readonly target: {
                    readonly namespaceId: "__unbound__" & NamespaceId;
                    readonly tableName: "admin";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly tag: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/datetime@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
                readonly nameKey: {
                  readonly nativeType: "text";
                  readonly codecId: "sqlite/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["nameKey"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "sqlite";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly admin: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Admin" };
    readonly category: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "Category";
    };
    readonly login_rate_limit: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "LoginRateLimit";
    };
    readonly session: {
      readonly namespace: "__unbound__" & NamespaceId;
      readonly model: "Session";
    };
    readonly tag: { readonly namespace: "__unbound__" & NamespaceId; readonly model: "Tag" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Admin: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "admin";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly passwordHash: { readonly column: "passwordHash" };
                readonly updatedAt: { readonly column: "updatedAt" };
                readonly username: { readonly column: "username" };
              };
            };
          };
          readonly Category: {
            readonly fields: {
              readonly color: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly nameKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "category";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly color: { readonly column: "color" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly nameKey: { readonly column: "nameKey" };
              };
            };
          };
          readonly LoginRateLimit: {
            readonly fields: {
              readonly count: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly window: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "login_rate_limit";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly count: { readonly column: "count" };
                readonly id: { readonly column: "id" };
                readonly window: { readonly column: "window" };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly adminId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/integer@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: {
              readonly admin: {
                readonly to: {
                  readonly namespace: "__unbound__" & NamespaceId;
                  readonly model: "Admin";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["adminId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "session";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly adminId: { readonly column: "adminId" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly expiresAt: { readonly column: "expiresAt" };
                readonly id: { readonly column: "id" };
              };
            };
          };
          readonly Tag: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/datetime@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
              readonly nameKey: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "sqlite/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "tag";
              readonly namespaceId: "__unbound__";
              readonly fields: {
                readonly createdAt: { readonly column: "createdAt" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly nameKey: { readonly column: "nameKey" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly foreignKeys: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly jsonAgg: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
